# Generated by Django 4.2.11 on 2024-04-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
