# Generated by Django 4.2.11 on 2024-06-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemap', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
    ]
